- hosts: all
  tasks:
     - name: stop contaier
       shell: docker container stop dockeransible
     - name: remove contaier
       shell: docker container rm dockeransible
     - name: docker image removal
       shell: docker image rm -f oalalif/pipeline-demo2
     - name: create new container
       shell: docker run -itd --name dockeradja oalalif/gacor-adja


# - hosts: all
#   tasks:
#      - name: stop contaier
#        shell: docker container stop dockeradja
#      - name: remove contaier
#        shell: docker container rm dockeradja
#      - name: docker image removal
#        shell: docker image rm -f oalalif/gacor-adja
#      - name: create new container
#        shell: docker run -itd --name dockeradja oalalif/gacor-adja